### ISSUE TITLE
Merge front end guide with this guide

### ISSUE THREAD

**Issue by msecret** [18F/development-guide#13]
The front end guide is best practices guide, https://pages.18f.gov/frontend/. It can't really be brought into this guide in it's current state because it has a good amount of hierarchy itself, so maybe it would be best to link to it from this guide? 

The goal here would be for new and current developers to have more awareness of the front end guide.

**Comment by monfresh** [comment]
Sounds good to me.

**Comment by msecret** [comment]
@monfresh any idea if #12 is going to happen soon? I could knock out this task pretty quickly but didn't want to if this repo is going to change

**Comment by jessieay** [comment]
seems unlikely from my point of view. if it does happen, we will be sure to notify you!

**Comment by tbaxter-18f** [comment]
The current plan is to merge the guides. Will update description.

**Comment by ryanhofdotgov** [comment]
Here's what I'm thinking the rough steps are:
- [ ] Import frontend repo into this one, preserving history
- [ ] Clean up the folder hierarchy
- [ ] Incorporate Jekyll into development-guide
- [ ] Publish development-guide to a new subdomain (e.g., `engineering.18f.gov`)
- [ ] Update https://18f.gsa.gov/guides to point to https://engineering.18f.gov instead of https://frontend.18f.gov
- [ ] Get redirect set up from https://frontend.18f.gov to https://engineering.18f.gov/frontend

**Comment by tbaxter-18f** [comment]
@heymatthenry has expressed some interest in helping.

**Comment by ryanhofdotgov** [comment]
I'm going to split up the remaining steps into separate issues since we're blocked on one of them.

**Comment by ryanhofdotgov** [comment]
Outstanding items tracked in #99, #100, #101
