### ISSUE TITLE
Add the 18F API Standards to the site

### ISSUE THREAD

**Issue by sknep** [18F/development-guide#295]
This seems useful and probably shouldn't _only_ live in GitHub. But where in the IA of this site?

https://github.com/18F/api-standards

**Comment by Sgtpluck** [comment]
Ohh this does look like a useful thing to add to the engineering guide. Thank you for finding it!

The IA of the site is something we've wanted to fix for awhile but since the guides have been in flux we haven't invested in it. I would say in the current setup, it would go into "Our Approach," maybe. What do you think?

**Comment by sknep** [comment]
I agree, it seems like it should end up in the sidebar of this section: https://engineering.18f.gov/workflow/

**Comment by matthinz** [comment]
Hey all, I'll take a crack at this.

**Comment by Sgtpluck** [comment]
dope, thanks!
